
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   

   
         (order-complexity o1 c0)
         (order-base-color o1 BASE_SILVER)
         (order-cap-color o1 CAP_BLACK)
         (order-gate o1 GATE-1)
      

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.419)
(= (path-length C-BS INPUT C-CS1 INPUT) 5.831)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 6.712)
(= (path-length C-BS INPUT C-CS2 INPUT) 3.339)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 3.093)
(= (path-length C-BS INPUT C-DS INPUT) 5.782)
(= (path-length C-BS INPUT C-DS OUTPUT) 7.001)
(= (path-length C-BS INPUT C-RS1 INPUT) 10.364)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 11.853)
(= (path-length C-BS INPUT C-RS2 INPUT) 6.443)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 4.047)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.419)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 7.464)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 8.345)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 1.002)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 2.954)
(= (path-length C-BS OUTPUT C-DS INPUT) 6.898)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 8.118)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 11.997)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 13.487)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 7.559)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 5.680)
(= (path-length C-CS1 INPUT C-BS INPUT) 5.831)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 7.464)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 2.667)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 7.051)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 6.188)
(= (path-length C-CS1 INPUT C-DS INPUT) 4.591)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 4.799)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 6.821)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 8.310)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 4.008)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 3.142)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 6.712)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 8.345)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 2.667)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 7.932)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 7.069)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 6.619)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 6.827)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 5.299)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 6.789)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 6.036)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 5.170)
(= (path-length C-CS2 INPUT C-BS INPUT) 3.339)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 1.002)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 7.051)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 7.932)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 2.540)
(= (path-length C-CS2 INPUT C-DS INPUT) 6.021)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 7.240)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 11.583)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 12.749)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 6.682)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 5.267)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 3.093)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 2.954)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 6.188)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 7.069)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 2.540)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 6.140)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 7.359)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 10.721)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 12.211)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 6.801)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 4.405)
(= (path-length C-DS INPUT C-BS INPUT) 5.782)
(= (path-length C-DS INPUT C-BS OUTPUT) 6.898)
(= (path-length C-DS INPUT C-CS1 INPUT) 4.591)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 6.619)
(= (path-length C-DS INPUT C-CS2 INPUT) 6.021)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 6.140)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.194)
(= (path-length C-DS INPUT C-RS1 INPUT) 6.934)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 7.036)
(= (path-length C-DS INPUT C-RS2 INPUT) 0.969)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 5.158)
(= (path-length C-DS OUTPUT C-BS INPUT) 7.001)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 8.118)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 4.799)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 6.827)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 7.240)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 7.359)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.194)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 6.887)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 6.205)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 2.611)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 5.366)
(= (path-length C-RS1 INPUT C-BS INPUT) 10.364)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 11.997)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 6.821)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 5.299)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 11.583)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 10.721)
(= (path-length C-RS1 INPUT C-DS INPUT) 6.934)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 6.887)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 3.645)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 6.351)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 7.512)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 11.853)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 13.487)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 8.310)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 6.789)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 12.749)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 12.211)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 7.036)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 6.205)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 3.645)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 6.453)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 9.002)
(= (path-length C-RS2 INPUT C-BS INPUT) 6.443)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 7.559)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 4.008)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 6.036)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 6.682)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 6.801)
(= (path-length C-RS2 INPUT C-DS INPUT) 0.969)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 2.611)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 6.351)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 6.453)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 4.575)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 4.047)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 5.680)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 3.142)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 5.170)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 5.267)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 4.405)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 5.158)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 5.366)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 7.512)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 9.002)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 4.575)
(= (path-length START INPUT C-BS INPUT) 0.699)
(= (path-length START INPUT C-BS OUTPUT) 2.385)
(= (path-length START INPUT C-CS1 INPUT) 5.797)
(= (path-length START INPUT C-CS1 OUTPUT) 6.678)
(= (path-length START INPUT C-CS2 INPUT) 3.305)
(= (path-length START INPUT C-CS2 OUTPUT) 3.059)
(= (path-length START INPUT C-DS INPUT) 5.748)
(= (path-length START INPUT C-DS OUTPUT) 6.967)
(= (path-length START INPUT C-RS1 INPUT) 10.330)
(= (path-length START INPUT C-RS1 OUTPUT) 11.819)
(= (path-length START INPUT C-RS2 INPUT) 6.409)
(= (path-length START INPUT C-RS2 OUTPUT) 4.013)

	)

	(:goal (order-fulfilled o1))
)
    