
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

   
         ; C1 order
	       (order-complexity o1 c1)
	       (order-base-color o1 BASE_BLACK)
	       (order-ring1-color o1 RING_ORANGE)
	       (order-cap-color o1 CAP_BLACK)
	       (order-gate o1 GATE-1)
       

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.876)
(= (path-length C-BS INPUT C-CS1 INPUT) 3.427)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 3.425)
(= (path-length C-BS INPUT C-CS2 INPUT) 7.801)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 6.722)
(= (path-length C-BS INPUT C-DS INPUT) 6.682)
(= (path-length C-BS INPUT C-DS OUTPUT) 6.674)
(= (path-length C-BS INPUT C-RS1 INPUT) 6.338)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 5.596)
(= (path-length C-BS INPUT C-RS2 INPUT) 4.280)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 0.429)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.876)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 4.928)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 4.926)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 8.750)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 8.223)
(= (path-length C-BS OUTPUT C-DS INPUT) 7.095)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 7.086)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 7.839)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 7.097)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 5.781)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 2.899)
(= (path-length C-CS1 INPUT C-BS INPUT) 3.427)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 4.928)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 3.260)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 4.816)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 3.709)
(= (path-length C-CS1 INPUT C-DS INPUT) 4.851)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 5.968)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 3.325)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 2.583)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 3.239)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 3.450)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 3.425)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 4.926)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 3.260)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 5.657)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 4.550)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 5.693)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 6.809)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 4.166)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 3.424)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 4.199)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 3.448)
(= (path-length C-CS2 INPUT C-BS INPUT) 7.801)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 8.750)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 4.816)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 5.657)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 3.478)
(= (path-length C-CS2 INPUT C-DS INPUT) 2.099)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 3.035)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 3.094)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 4.979)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 4.995)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 7.824)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 6.722)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 8.223)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 3.709)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 4.550)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 3.478)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 3.514)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 4.630)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 0.393)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 3.110)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 3.919)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 6.744)
(= (path-length C-DS INPUT C-BS INPUT) 6.682)
(= (path-length C-DS INPUT C-BS OUTPUT) 7.095)
(= (path-length C-DS INPUT C-CS1 INPUT) 4.851)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 5.693)
(= (path-length C-DS INPUT C-CS2 INPUT) 2.099)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 3.514)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.252)
(= (path-length C-DS INPUT C-RS1 INPUT) 3.129)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 5.015)
(= (path-length C-DS INPUT C-RS2 INPUT) 4.355)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 6.638)
(= (path-length C-DS OUTPUT C-BS INPUT) 6.674)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 7.086)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 5.968)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 6.809)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 3.035)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 4.630)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.252)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 4.246)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 6.132)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 4.346)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 6.630)
(= (path-length C-RS1 INPUT C-BS INPUT) 6.338)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 7.839)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 3.325)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 4.166)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 3.094)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 0.393)
(= (path-length C-RS1 INPUT C-DS INPUT) 3.129)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 4.246)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 3.489)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 3.535)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 6.360)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 5.596)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 7.097)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 2.583)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 3.424)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 4.979)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 3.110)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 5.015)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 6.132)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 3.489)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 5.407)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 5.618)
(= (path-length C-RS2 INPUT C-BS INPUT) 4.280)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 5.781)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 3.239)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 4.199)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 4.995)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 3.919)
(= (path-length C-RS2 INPUT C-DS INPUT) 4.355)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 4.346)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 3.535)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 5.407)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 4.302)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 0.429)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 2.899)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 3.450)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 3.448)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 7.824)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 6.744)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 6.638)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 6.630)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 6.360)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 5.618)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 4.302)
(= (path-length START INPUT C-BS INPUT) 1.090)
(= (path-length START INPUT C-BS OUTPUT) 2.592)
(= (path-length START INPUT C-CS1 INPUT) 3.086)
(= (path-length START INPUT C-CS1 OUTPUT) 3.084)
(= (path-length START INPUT C-CS2 INPUT) 7.460)
(= (path-length START INPUT C-CS2 OUTPUT) 6.381)
(= (path-length START INPUT C-DS INPUT) 7.278)
(= (path-length START INPUT C-DS OUTPUT) 7.270)
(= (path-length START INPUT C-RS1 INPUT) 5.997)
(= (path-length START INPUT C-RS1 OUTPUT) 5.255)
(= (path-length START INPUT C-RS2 INPUT) 3.939)
(= (path-length START INPUT C-RS2 OUTPUT) 1.113)

	)

	(:goal (order-fulfilled o1))
)
    