
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 R-3 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
(robot-waiting R-3)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

   
         ; C1 order
	       (order-complexity o1 c1)
	       (order-base-color o1 BASE_SILVER)
	       (order-ring1-color o1 RING_GREEN)
	       (order-cap-color o1 CAP_GREY)
	       (order-gate o1 GATE-1)
       

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.763)
(= (path-length C-BS INPUT C-CS1 INPUT) 4.195)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 5.210)
(= (path-length C-BS INPUT C-CS2 INPUT) 7.491)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 8.098)
(= (path-length C-BS INPUT C-DS INPUT) 6.710)
(= (path-length C-BS INPUT C-DS OUTPUT) 6.805)
(= (path-length C-BS INPUT C-RS1 INPUT) 6.315)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 4.010)
(= (path-length C-BS INPUT C-RS2 INPUT) 11.499)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 12.977)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.763)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 5.326)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 5.145)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 7.426)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 8.033)
(= (path-length C-BS OUTPUT C-DS INPUT) 6.645)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 6.740)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 4.249)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 1.792)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 11.434)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 12.912)
(= (path-length C-CS1 INPUT C-BS INPUT) 4.195)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 5.326)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 4.056)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 4.716)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 5.323)
(= (path-length C-CS1 INPUT C-DS INPUT) 5.503)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 6.788)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 6.298)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 5.331)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 8.582)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 10.060)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 5.210)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 5.145)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 4.056)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 2.288)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 2.895)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 3.075)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 4.390)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 5.066)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 5.151)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 6.295)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 7.773)
(= (path-length C-CS2 INPUT C-BS INPUT) 7.491)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 7.426)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 4.716)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 2.288)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 3.517)
(= (path-length C-CS2 INPUT C-DS INPUT) 3.697)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 5.012)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 7.347)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 7.432)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 4.213)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 5.691)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 8.098)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 8.033)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 5.323)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 2.895)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 3.517)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 1.743)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 3.037)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 5.402)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 8.039)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 3.655)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 5.133)
(= (path-length C-DS INPUT C-BS INPUT) 6.710)
(= (path-length C-DS INPUT C-BS OUTPUT) 6.645)
(= (path-length C-DS INPUT C-CS1 INPUT) 5.503)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 3.075)
(= (path-length C-DS INPUT C-CS2 INPUT) 3.697)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 1.743)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.238)
(= (path-length C-DS INPUT C-RS1 INPUT) 4.001)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 6.651)
(= (path-length C-DS INPUT C-RS2 INPUT) 5.144)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 6.622)
(= (path-length C-DS OUTPUT C-BS INPUT) 6.805)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 6.740)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 6.788)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 4.390)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 5.012)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 3.037)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.238)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 4.096)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 6.745)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 6.052)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 7.061)
(= (path-length C-RS1 INPUT C-BS INPUT) 6.315)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 4.249)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 6.298)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 5.066)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 7.347)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 5.402)
(= (path-length C-RS1 INPUT C-DS INPUT) 4.001)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 4.096)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 3.190)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 8.802)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 10.280)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 4.010)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 1.792)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 5.331)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 5.151)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 7.432)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 8.039)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 6.651)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 6.745)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 3.190)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 11.439)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 12.917)
(= (path-length C-RS2 INPUT C-BS INPUT) 11.499)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 11.434)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 8.582)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 6.295)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 4.213)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 3.655)
(= (path-length C-RS2 INPUT C-DS INPUT) 5.144)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 6.052)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 8.802)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 11.439)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 2.884)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 12.977)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 12.912)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 10.060)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 7.773)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 5.691)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 5.133)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 6.622)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 7.061)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 10.280)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 12.917)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 2.884)
(= (path-length START INPUT C-BS INPUT) 1.578)
(= (path-length START INPUT C-BS OUTPUT) 3.940)
(= (path-length START INPUT C-CS1 INPUT) 3.379)
(= (path-length START INPUT C-CS1 OUTPUT) 4.394)
(= (path-length START INPUT C-CS2 INPUT) 6.675)
(= (path-length START INPUT C-CS2 OUTPUT) 7.282)
(= (path-length START INPUT C-DS INPUT) 5.894)
(= (path-length START INPUT C-DS OUTPUT) 5.988)
(= (path-length START INPUT C-RS1 INPUT) 5.498)
(= (path-length START INPUT C-RS1 OUTPUT) 4.531)
(= (path-length START INPUT C-RS2 INPUT) 10.682)
(= (path-length START INPUT C-RS2 OUTPUT) 12.160)

	)

	(:goal (order-fulfilled o1))
)
    