
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   

   
         (order-complexity o1 c0)
         (order-base-color o1 BASE_BLACK)
         (order-cap-color o1 CAP_BLACK)
         (order-gate o1 GATE-2)
      

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.612)
(= (path-length C-BS INPUT C-CS1 INPUT) 2.455)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 3.283)
(= (path-length C-BS INPUT C-CS2 INPUT) 7.787)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 5.289)
(= (path-length C-BS INPUT C-DS INPUT) 4.991)
(= (path-length C-BS INPUT C-DS OUTPUT) 7.508)
(= (path-length C-BS INPUT C-RS1 INPUT) 10.715)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 10.700)
(= (path-length C-BS INPUT C-RS2 INPUT) 4.629)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 3.137)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.612)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 4.240)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 4.816)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 9.321)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 7.074)
(= (path-length C-BS OUTPUT C-DS INPUT) 6.524)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 8.991)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 12.249)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 12.486)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 6.163)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 3.970)
(= (path-length C-CS1 INPUT C-BS INPUT) 2.455)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 4.240)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 3.053)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 7.456)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 3.816)
(= (path-length C-CS1 INPUT C-DS INPUT) 5.647)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 7.194)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 9.369)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 9.228)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 5.285)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 5.123)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 3.283)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 4.816)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 3.053)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 6.278)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 4.066)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 3.481)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 5.999)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 9.206)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 9.478)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 3.120)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 3.737)
(= (path-length C-CS2 INPUT C-BS INPUT) 7.787)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 9.321)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 7.456)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 6.278)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 4.381)
(= (path-length C-CS2 INPUT C-DS INPUT) 5.291)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 4.529)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 4.673)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 5.054)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 4.929)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 8.133)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 5.289)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 7.074)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 3.816)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 4.066)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 4.381)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 6.004)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 5.427)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 6.294)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 6.152)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 5.643)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 6.916)
(= (path-length C-DS INPUT C-BS INPUT) 4.991)
(= (path-length C-DS INPUT C-BS OUTPUT) 6.524)
(= (path-length C-DS INPUT C-CS1 INPUT) 5.647)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 3.481)
(= (path-length C-DS INPUT C-CS2 INPUT) 5.291)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 6.004)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.652)
(= (path-length C-DS INPUT C-RS1 INPUT) 8.219)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 9.183)
(= (path-length C-DS INPUT C-RS2 INPUT) 1.405)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 3.538)
(= (path-length C-DS OUTPUT C-BS INPUT) 7.508)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 8.991)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 7.194)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 5.999)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 4.529)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 5.427)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.652)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 5.344)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 7.899)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 4.362)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 5.035)
(= (path-length C-RS1 INPUT C-BS INPUT) 10.715)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 12.249)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 9.369)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 9.206)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 4.673)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 6.294)
(= (path-length C-RS1 INPUT C-DS INPUT) 8.219)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 5.344)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 4.079)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 7.858)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 9.928)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 10.700)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 12.486)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 9.228)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 9.478)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 5.054)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 6.152)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 9.183)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 7.899)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 4.079)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 8.821)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 12.025)
(= (path-length C-RS2 INPUT C-BS INPUT) 4.629)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 6.163)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 5.285)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 3.120)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 4.929)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 5.643)
(= (path-length C-RS2 INPUT C-DS INPUT) 1.405)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 4.362)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 7.858)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 8.821)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 4.248)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 3.137)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 3.970)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 5.123)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 3.737)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 8.133)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 6.916)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 3.538)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 5.035)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 9.928)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 12.025)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 4.248)
(= (path-length START INPUT C-BS INPUT) 0.783)
(= (path-length START INPUT C-BS OUTPUT) 2.568)
(= (path-length START INPUT C-CS1 INPUT) 1.729)
(= (path-length START INPUT C-CS1 OUTPUT) 3.597)
(= (path-length START INPUT C-CS2 INPUT) 8.101)
(= (path-length START INPUT C-CS2 OUTPUT) 4.563)
(= (path-length START INPUT C-DS INPUT) 5.305)
(= (path-length START INPUT C-DS OUTPUT) 7.823)
(= (path-length START INPUT C-RS1 INPUT) 10.116)
(= (path-length START INPUT C-RS1 OUTPUT) 9.975)
(= (path-length START INPUT C-RS2 INPUT) 4.943)
(= (path-length START INPUT C-RS2 OUTPUT) 3.451)

	)

	(:goal (order-fulfilled o1))
)
    