
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

   
         ; C1 order
	       (order-complexity o1 c1)
	       (order-base-color o1 BASE_SILVER)
	       (order-ring1-color o1 RING_BLUE)
	       (order-cap-color o1 CAP_GREY)
	       (order-gate o1 GATE-1)
       

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.721)
(= (path-length C-BS INPUT C-CS1 INPUT) 9.566)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 8.548)
(= (path-length C-BS INPUT C-CS2 INPUT) 2.308)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 3.690)
(= (path-length C-BS INPUT C-DS INPUT) 7.466)
(= (path-length C-BS INPUT C-DS OUTPUT) 7.302)
(= (path-length C-BS INPUT C-RS1 INPUT) 6.801)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 5.897)
(= (path-length C-BS INPUT C-RS2 INPUT) 6.799)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 5.024)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.721)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 10.167)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 9.150)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 0.943)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 2.106)
(= (path-length C-BS OUTPUT C-DS INPUT) 8.068)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 6.471)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 7.402)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 6.498)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 5.215)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 3.706)
(= (path-length C-CS1 INPUT C-BS INPUT) 9.566)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 10.167)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 4.050)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 9.333)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 11.462)
(= (path-length C-CS1 INPUT C-DS INPUT) 7.110)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 8.077)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 2.889)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 5.509)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 11.342)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 10.632)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 8.548)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 9.150)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 4.050)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 8.316)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 9.149)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 4.796)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 6.584)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 2.906)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 4.782)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 9.028)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 8.319)
(= (path-length C-CS2 INPUT C-BS INPUT) 2.308)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 0.943)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 9.333)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 8.316)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 2.752)
(= (path-length C-CS2 INPUT C-DS INPUT) 7.234)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 5.637)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 6.569)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 5.665)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 5.862)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 3.359)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 3.690)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 2.106)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 11.462)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 9.149)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 2.752)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 8.067)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 5.361)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 9.211)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 7.983)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 3.539)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 2.030)
(= (path-length C-DS INPUT C-BS INPUT) 7.466)
(= (path-length C-DS INPUT C-BS OUTPUT) 8.068)
(= (path-length C-DS INPUT C-CS1 INPUT) 7.110)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 4.796)
(= (path-length C-DS INPUT C-CS2 INPUT) 7.234)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 8.067)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.189)
(= (path-length C-DS INPUT C-RS1 INPUT) 5.685)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 3.700)
(= (path-length C-DS INPUT C-RS2 INPUT) 7.389)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 7.237)
(= (path-length C-DS OUTPUT C-BS INPUT) 7.302)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 6.471)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 8.077)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 6.584)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 5.637)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 5.361)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.189)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 7.474)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 5.489)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 4.222)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 4.531)
(= (path-length C-RS1 INPUT C-BS INPUT) 6.801)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 7.402)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 2.889)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 2.906)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 6.569)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 9.211)
(= (path-length C-RS1 INPUT C-DS INPUT) 5.685)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 7.474)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 2.744)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 9.848)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 9.138)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 5.897)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 6.498)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 5.509)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 4.782)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 5.665)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 7.983)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 3.700)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 5.489)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 2.744)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 7.863)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 7.153)
(= (path-length C-RS2 INPUT C-BS INPUT) 6.799)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 5.215)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 11.342)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 9.028)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 5.862)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 3.539)
(= (path-length C-RS2 INPUT C-DS INPUT) 7.389)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 4.222)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 9.848)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 7.863)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 3.711)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 5.024)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 3.706)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 10.632)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 8.319)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 3.359)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 2.030)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 7.237)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 4.531)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 9.138)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 7.153)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 3.711)
(= (path-length START INPUT C-BS INPUT) 1.655)
(= (path-length START INPUT C-BS OUTPUT) 2.257)
(= (path-length START INPUT C-CS1 INPUT) 8.587)
(= (path-length START INPUT C-CS1 OUTPUT) 7.570)
(= (path-length START INPUT C-CS2 INPUT) 1.423)
(= (path-length START INPUT C-CS2 OUTPUT) 4.066)
(= (path-length START INPUT C-DS INPUT) 6.488)
(= (path-length START INPUT C-DS OUTPUT) 6.418)
(= (path-length START INPUT C-RS1 INPUT) 5.822)
(= (path-length START INPUT C-RS1 OUTPUT) 4.918)
(= (path-length START INPUT C-RS2 INPUT) 6.651)
(= (path-length START INPUT C-RS2 OUTPUT) 4.140)

	)

	(:goal (order-fulfilled o1))
)
    