
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 R-3 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
(robot-waiting R-3)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

   
         ; C1 order
	       (order-complexity o1 c1)
	       (order-base-color o1 BASE_BLACK)
	       (order-ring1-color o1 RING_BLUE)
	       (order-cap-color o1 CAP_GREY)
	       (order-gate o1 GATE-3)
       

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.763)
(= (path-length C-BS INPUT C-CS1 INPUT) 11.017)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 8.698)
(= (path-length C-BS INPUT C-CS2 INPUT) 5.412)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 4.025)
(= (path-length C-BS INPUT C-DS INPUT) 7.387)
(= (path-length C-BS INPUT C-DS OUTPUT) 5.309)
(= (path-length C-BS INPUT C-RS1 INPUT) 3.553)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 5.208)
(= (path-length C-BS INPUT C-RS2 INPUT) 9.843)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 12.073)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.763)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 11.890)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 9.492)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 6.206)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 4.898)
(= (path-length C-BS OUTPUT C-DS INPUT) 7.390)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 6.103)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 4.426)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 6.081)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 10.716)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 12.946)
(= (path-length C-CS1 INPUT C-BS INPUT) 11.017)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 11.890)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 4.932)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 6.990)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 7.353)
(= (path-length C-CS1 INPUT C-DS INPUT) 6.109)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 7.081)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 8.171)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 6.958)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 1.535)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 3.144)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 8.698)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 9.492)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 4.932)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 4.380)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 5.904)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 5.731)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 4.471)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 6.722)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 5.509)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 3.758)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 5.988)
(= (path-length C-CS2 INPUT C-BS INPUT) 5.412)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 6.206)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 6.990)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 4.380)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 4.624)
(= (path-length C-CS2 INPUT C-DS INPUT) 4.248)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 1.185)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 4.790)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 4.389)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 7.125)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 8.446)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 4.025)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 4.898)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 7.353)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 5.904)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 4.624)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 5.975)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 4.715)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 1.179)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 2.304)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 6.179)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 8.409)
(= (path-length C-DS INPUT C-BS INPUT) 7.387)
(= (path-length C-DS INPUT C-BS OUTPUT) 7.390)
(= (path-length C-DS INPUT C-CS1 INPUT) 6.109)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 5.731)
(= (path-length C-DS INPUT C-CS2 INPUT) 4.248)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 5.975)
(= (path-length C-DS INPUT C-DS OUTPUT) 4.330)
(= (path-length C-DS INPUT C-RS1 INPUT) 6.764)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 5.740)
(= (path-length C-DS INPUT C-RS2 INPUT) 7.144)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 7.564)
(= (path-length C-DS OUTPUT C-BS INPUT) 5.309)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 6.103)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 7.081)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 4.471)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 1.185)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 4.715)
(= (path-length C-DS OUTPUT C-DS INPUT) 4.330)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 4.686)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 4.480)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 7.216)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 8.537)
(= (path-length C-RS1 INPUT C-BS INPUT) 3.553)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 4.426)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 8.171)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 6.722)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 4.790)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 1.179)
(= (path-length C-RS1 INPUT C-DS INPUT) 6.764)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 4.686)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 3.122)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 6.997)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 9.227)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 5.208)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 6.081)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 6.958)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 5.509)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 4.389)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 2.304)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 5.740)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 4.480)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 3.122)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 5.784)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 8.014)
(= (path-length C-RS2 INPUT C-BS INPUT) 9.843)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 10.716)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 1.535)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 3.758)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 7.125)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 6.179)
(= (path-length C-RS2 INPUT C-DS INPUT) 7.144)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 7.216)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 6.997)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 5.784)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 4.179)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 12.073)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 12.946)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 3.144)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 5.988)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 8.446)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 8.409)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 7.564)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 8.537)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 9.227)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 8.014)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 4.179)
(= (path-length START INPUT C-BS INPUT) 1.578)
(= (path-length START INPUT C-BS OUTPUT) 3.940)
(= (path-length START INPUT C-CS1 INPUT) 10.201)
(= (path-length START INPUT C-CS1 OUTPUT) 7.881)
(= (path-length START INPUT C-CS2 INPUT) 4.596)
(= (path-length START INPUT C-CS2 OUTPUT) 3.208)
(= (path-length START INPUT C-DS INPUT) 6.570)
(= (path-length START INPUT C-DS OUTPUT) 4.492)
(= (path-length START INPUT C-RS1 INPUT) 2.736)
(= (path-length START INPUT C-RS1 OUTPUT) 4.392)
(= (path-length START INPUT C-RS2 INPUT) 9.027)
(= (path-length START INPUT C-RS2 OUTPUT) 11.256)

	)

	(:goal (order-fulfilled o1))
)
    