
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 R-3 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
(robot-waiting R-3)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

   
         ; C1 order
	       (order-complexity o1 c1)
	       (order-base-color o1 BASE_RED)
	       (order-ring1-color o1 RING_YELLOW)
	       (order-cap-color o1 CAP_GREY)
	       (order-gate o1 GATE-2)
       

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.615)
(= (path-length C-BS INPUT C-CS1 INPUT) 12.255)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 10.964)
(= (path-length C-BS INPUT C-CS2 INPUT) 2.684)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 5.161)
(= (path-length C-BS INPUT C-DS INPUT) 8.383)
(= (path-length C-BS INPUT C-DS OUTPUT) 8.838)
(= (path-length C-BS INPUT C-RS1 INPUT) 4.215)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 7.919)
(= (path-length C-BS INPUT C-RS2 INPUT) 9.954)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 10.542)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.615)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 10.303)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 9.013)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 3.341)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 3.601)
(= (path-length C-BS OUTPUT C-DS INPUT) 6.834)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 6.887)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 2.227)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 6.371)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 8.002)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 8.591)
(= (path-length C-CS1 INPUT C-BS INPUT) 12.255)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 10.303)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 2.624)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 11.552)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 11.259)
(= (path-length C-CS1 INPUT C-DS INPUT) 8.988)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 8.096)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 9.885)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 9.822)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 5.346)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 3.402)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 10.964)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 9.013)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 2.624)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 10.261)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 9.968)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 8.549)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 6.805)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 8.594)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 8.531)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 2.780)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 1.515)
(= (path-length C-CS2 INPUT C-BS INPUT) 2.684)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 3.341)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 11.552)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 10.261)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 3.107)
(= (path-length C-CS2 INPUT C-DS INPUT) 5.937)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 8.135)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 2.502)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 5.474)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 9.250)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 9.839)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 5.161)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 3.601)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 11.259)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 9.968)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 3.107)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 3.566)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 6.729)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 2.209)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 3.102)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 8.958)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 9.546)
(= (path-length C-DS INPUT C-BS INPUT) 8.383)
(= (path-length C-DS INPUT C-BS OUTPUT) 6.834)
(= (path-length C-DS INPUT C-CS1 INPUT) 8.988)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 8.549)
(= (path-length C-DS INPUT C-CS2 INPUT) 5.937)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 3.566)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.207)
(= (path-length C-DS INPUT C-RS1 INPUT) 5.442)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 2.123)
(= (path-length C-DS INPUT C-RS2 INPUT) 7.539)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 8.128)
(= (path-length C-DS OUTPUT C-BS INPUT) 8.838)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 6.887)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 8.096)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 6.805)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 8.135)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 6.729)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.207)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 6.469)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 5.286)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 5.795)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 6.384)
(= (path-length C-RS1 INPUT C-BS INPUT) 4.215)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 2.227)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 9.885)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 8.594)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 2.502)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 2.209)
(= (path-length C-RS1 INPUT C-DS INPUT) 5.442)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 6.469)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 4.978)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 7.584)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 8.172)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 7.919)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 6.371)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 9.822)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 8.531)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 5.474)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 3.102)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 2.123)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 5.286)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 4.978)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 7.521)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 8.109)
(= (path-length C-RS2 INPUT C-BS INPUT) 9.954)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 8.002)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 5.346)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 2.780)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 9.250)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 8.958)
(= (path-length C-RS2 INPUT C-DS INPUT) 7.539)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 5.795)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 7.584)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 7.521)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 3.313)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 10.542)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 8.591)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 3.402)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 1.515)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 9.839)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 9.546)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 8.128)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 6.384)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 8.172)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 8.109)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 3.313)
(= (path-length START INPUT C-BS INPUT) 2.310)
(= (path-length START INPUT C-BS OUTPUT) 1.631)
(= (path-length START INPUT C-CS1 INPUT) 10.002)
(= (path-length START INPUT C-CS1 OUTPUT) 8.711)
(= (path-length START INPUT C-CS2 INPUT) 4.343)
(= (path-length START INPUT C-CS2 OUTPUT) 4.050)
(= (path-length START INPUT C-DS INPUT) 7.284)
(= (path-length START INPUT C-DS OUTPUT) 6.586)
(= (path-length START INPUT C-RS1 INPUT) 2.677)
(= (path-length START INPUT C-RS1 OUTPUT) 6.820)
(= (path-length START INPUT C-RS2 INPUT) 7.701)
(= (path-length START INPUT C-RS2 OUTPUT) 8.289)

	)

	(:goal (order-fulfilled o1))
)
    