
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 R-3 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  (rs-sub THREE TWO ONE)
	 (rs-sub THREE ONE TWO)
	 (rs-sub THREE ZERO THREE)
	 (rs-sub TWO TWO ZERO)
	 (rs-sub TWO ONE ONE)
	 (rs-sub TWO ZERO TWO)
	 (rs-sub ONE ONE ZERO)
	 (rs-sub ONE ZERO ONE)
	 (rs-sub ZERO ZERO ZERO)
	 (rs-inc ZERO ONE)
	 (rs-inc ONE TWO)
	 (rs-inc TWO THREE)
	 (rs-filled-with C-RS1 ZERO)
	 (rs-filled-with C-RS2 ZERO)
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
(robot-waiting R-3)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   (rs-ring-spec C-RS1 RING_GREEN ZERO)
	 (rs-ring-spec C-RS1 RING_YELLOW ZERO)
	 (rs-ring-spec C-RS2 RING_BLUE ONE)
	 (rs-ring-spec C-RS2 RING_ORANGE TWO)

   
         ; C1 order
	       (order-complexity o1 c1)
	       (order-base-color o1 BASE_RED)
	       (order-ring1-color o1 RING_BLUE)
	       (order-cap-color o1 CAP_BLACK)
	       (order-gate o1 GATE-2)
       

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 3.074)
(= (path-length C-BS INPUT C-CS1 INPUT) 6.059)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 9.322)
(= (path-length C-BS INPUT C-CS2 INPUT) 6.497)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 7.542)
(= (path-length C-BS INPUT C-DS INPUT) 8.269)
(= (path-length C-BS INPUT C-DS OUTPUT) 6.129)
(= (path-length C-BS INPUT C-RS1 INPUT) 2.220)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 3.206)
(= (path-length C-BS INPUT C-RS2 INPUT) 10.429)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 9.434)
(= (path-length C-BS OUTPUT C-BS INPUT) 3.074)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 7.452)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 9.324)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 4.660)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 5.705)
(= (path-length C-BS OUTPUT C-DS INPUT) 7.732)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 5.862)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 3.519)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 5.568)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 10.161)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 10.445)
(= (path-length C-CS1 INPUT C-BS INPUT) 6.059)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 7.452)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 4.864)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 5.927)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 6.476)
(= (path-length C-CS1 INPUT C-DS INPUT) 4.778)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 3.914)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 5.554)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 3.001)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 5.700)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 5.013)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 9.322)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 9.324)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 4.864)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 6.639)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 7.189)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 5.491)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 4.627)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 8.024)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 6.264)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 3.415)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 2.111)
(= (path-length C-CS2 INPUT C-BS INPUT) 6.497)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 4.660)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 5.927)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 6.639)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 3.353)
(= (path-length C-CS2 INPUT C-DS INPUT) 3.712)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 3.177)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 5.361)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 5.893)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 7.476)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 7.760)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 7.542)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 5.705)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 6.476)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 7.189)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 3.353)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 2.255)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 3.726)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 6.343)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 6.442)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 7.359)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 8.309)
(= (path-length C-DS INPUT C-BS INPUT) 8.269)
(= (path-length C-DS INPUT C-BS OUTPUT) 7.732)
(= (path-length C-DS INPUT C-CS1 INPUT) 4.778)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 5.491)
(= (path-length C-DS INPUT C-CS2 INPUT) 3.712)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 2.255)
(= (path-length C-DS INPUT C-DS OUTPUT) 4.085)
(= (path-length C-DS INPUT C-RS1 INPUT) 6.702)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 6.801)
(= (path-length C-DS INPUT C-RS2 INPUT) 5.197)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 6.612)
(= (path-length C-DS OUTPUT C-BS INPUT) 6.129)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 5.862)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 3.914)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 4.627)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 3.177)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 3.726)
(= (path-length C-DS OUTPUT C-DS INPUT) 4.085)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 4.562)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 4.661)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 5.464)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 5.748)
(= (path-length C-RS1 INPUT C-BS INPUT) 2.220)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 3.519)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 5.554)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 8.024)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 5.361)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 6.343)
(= (path-length C-RS1 INPUT C-DS INPUT) 6.702)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 4.562)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 2.701)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 8.861)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 8.930)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 3.206)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 5.568)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 3.001)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 6.264)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 5.893)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 6.442)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 6.801)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 4.661)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 2.701)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 8.024)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 6.376)
(= (path-length C-RS2 INPUT C-BS INPUT) 10.429)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 10.161)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 5.700)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 3.415)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 7.476)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 7.359)
(= (path-length C-RS2 INPUT C-DS INPUT) 5.197)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 5.464)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 8.861)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 8.024)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 4.536)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 9.434)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 10.445)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 5.013)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 2.111)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 7.760)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 8.309)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 6.612)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 5.748)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 8.930)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 6.376)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 4.536)
(= (path-length START INPUT C-BS INPUT) 1.783)
(= (path-length START INPUT C-BS OUTPUT) 4.146)
(= (path-length START INPUT C-CS1 INPUT) 4.377)
(= (path-length START INPUT C-CS1 OUTPUT) 7.641)
(= (path-length START INPUT C-CS2 INPUT) 5.987)
(= (path-length START INPUT C-CS2 OUTPUT) 6.969)
(= (path-length START INPUT C-DS INPUT) 7.328)
(= (path-length START INPUT C-DS OUTPUT) 5.188)
(= (path-length START INPUT C-RS1 INPUT) 1.278)
(= (path-length START INPUT C-RS1 OUTPUT) 1.524)
(= (path-length START INPUT C-RS2 INPUT) 9.401)
(= (path-length START INPUT C-RS2 OUTPUT) 7.753)

	)

	(:goal (order-fulfilled o1))
)
    