
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   

   
         (order-complexity o1 c0)
         (order-base-color o1 BASE_SILVER)
         (order-cap-color o1 CAP_BLACK)
         (order-gate o1 GATE-2)
      

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 2.380)
(= (path-length C-BS INPUT C-CS1 INPUT) 8.045)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 7.417)
(= (path-length C-BS INPUT C-CS2 INPUT) 5.163)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 7.297)
(= (path-length C-BS INPUT C-DS INPUT) 7.838)
(= (path-length C-BS INPUT C-DS OUTPUT) 6.254)
(= (path-length C-BS INPUT C-RS1 INPUT) 4.008)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 1.934)
(= (path-length C-BS INPUT C-RS2 INPUT) 7.781)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 8.858)
(= (path-length C-BS OUTPUT C-BS INPUT) 2.380)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 9.791)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 9.163)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 4.056)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 6.189)
(= (path-length C-BS OUTPUT C-DS INPUT) 8.262)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 6.202)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 2.901)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 4.162)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 9.527)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 10.604)
(= (path-length C-CS1 INPUT C-BS INPUT) 8.045)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 9.791)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 2.638)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 7.863)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 7.840)
(= (path-length C-CS1 INPUT C-DS INPUT) 6.738)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 6.521)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 7.159)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 6.373)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 3.936)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 5.334)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 7.417)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 9.163)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 2.638)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 7.235)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 7.212)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 6.110)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 5.893)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 6.530)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 5.744)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 4.946)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 6.023)
(= (path-length C-CS2 INPUT C-BS INPUT) 5.163)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 4.056)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 7.863)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 7.235)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 3.083)
(= (path-length C-CS2 INPUT C-DS INPUT) 4.220)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 2.160)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 3.362)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 5.378)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 7.599)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 8.676)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 7.297)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 6.189)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 7.840)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 7.212)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 3.083)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 2.293)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 2.136)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 5.495)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 5.901)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 7.576)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 7.141)
(= (path-length C-DS INPUT C-BS INPUT) 7.838)
(= (path-length C-DS INPUT C-BS OUTPUT) 8.262)
(= (path-length C-DS INPUT C-CS1 INPUT) 6.738)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 6.110)
(= (path-length C-DS INPUT C-CS2 INPUT) 4.220)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 2.293)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.274)
(= (path-length C-DS INPUT C-RS1 INPUT) 6.770)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 6.166)
(= (path-length C-DS INPUT C-RS2 INPUT) 6.474)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 4.951)
(= (path-length C-DS OUTPUT C-BS INPUT) 6.254)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 6.202)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 6.521)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 5.893)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 2.160)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 2.136)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.274)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 4.313)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 4.582)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 6.257)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 7.334)
(= (path-length C-RS1 INPUT C-BS INPUT) 4.008)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 2.901)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 7.159)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 6.530)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 3.362)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 5.495)
(= (path-length C-RS1 INPUT C-DS INPUT) 6.770)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 4.313)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 4.223)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 6.895)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 7.971)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 1.934)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 4.162)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 6.373)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 5.744)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 5.378)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 5.901)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 6.166)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 4.582)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 4.223)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 6.109)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 7.185)
(= (path-length C-RS2 INPUT C-BS INPUT) 7.781)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 9.527)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 3.936)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 4.946)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 7.599)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 7.576)
(= (path-length C-RS2 INPUT C-DS INPUT) 6.474)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 6.257)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 6.895)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 6.109)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 4.456)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 8.858)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 10.604)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 5.334)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 6.023)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 8.676)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 7.141)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 4.951)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 7.334)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 7.971)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 7.185)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 4.456)
(= (path-length START INPUT C-BS INPUT) 0.890)
(= (path-length START INPUT C-BS OUTPUT) 3.134)
(= (path-length START INPUT C-CS1 INPUT) 7.670)
(= (path-length START INPUT C-CS1 OUTPUT) 7.042)
(= (path-length START INPUT C-CS2 INPUT) 5.102)
(= (path-length START INPUT C-CS2 OUTPUT) 7.235)
(= (path-length START INPUT C-DS INPUT) 7.464)
(= (path-length START INPUT C-DS OUTPUT) 6.192)
(= (path-length START INPUT C-RS1 INPUT) 3.946)
(= (path-length START INPUT C-RS1 OUTPUT) 1.872)
(= (path-length START INPUT C-RS2 INPUT) 7.406)
(= (path-length START INPUT C-RS2 OUTPUT) 8.483)

	)

	(:goal (order-fulfilled o1))
)
    