
    (define (problem rcll-production-durative-prob1)
	   (:domain rcll-production-durative)

	(:objects
		R-1 R-2 - robot
		; If adding R-2 and R-3, also add robot-waiting facts below
		o1 - order
		wp1 - workpiece
		cg1 cg2 cg3 cb1 cb2 cb3 - cap-carrier
		C-BS C-CS1 C-CS2 C-DS C-RS1 C-RS2 - mps
		CYAN - team-color
	)

	(:init
   (mps-type C-BS BS)
(mps-type C-CS1 CS)
(mps-type C-CS2 CS)
(mps-type C-DS DS)
(mps-type C-RS1 RS)
(mps-type C-RS2 RS)
	 (location-free START INPUT)
   (location-free C-BS INPUT)
(location-free C-BS OUTPUT)
(location-free C-CS1 INPUT)
(location-free C-CS1 OUTPUT)
(location-free C-CS2 INPUT)
(location-free C-CS2 OUTPUT)
(location-free C-DS INPUT)
(location-free C-DS OUTPUT)
(location-free C-RS1 INPUT)
(location-free C-RS1 OUTPUT)
(location-free C-RS2 INPUT)
(location-free C-RS2 OUTPUT)

	 (cs-can-perform C-CS1 CS_RETRIEVE)
	 (cs-can-perform C-CS2 CS_RETRIEVE)
	 (cs-free C-CS1)
	 (cs-free C-CS2)
	 ; Additional base number handling static predicates
  
	 (wp-base-color wp1 BASE_NONE)
	 (wp-cap-color wp1 CAP_NONE)
	 (wp-ring1-color wp1 RING_NONE)
	 (wp-ring2-color wp1 RING_NONE)
	 (wp-ring3-color wp1 RING_NONE)
	 (wp-unused wp1)
   (robot-waiting R-1)
(robot-waiting R-2)
	 ;(robot-waiting R-1)
	 ;(robot-waiting R-2)
	 ;(robot-waiting R-3)

	 (mps-state C-BS IDLE)
(mps-state C-CS1 IDLE)
(mps-state C-CS2 IDLE)
(mps-state C-DS IDLE)
(mps-state C-RS1 IDLE)
(mps-state C-RS2 IDLE)
   ;(mps-state C-BS IDLE)
 	 ;(mps-state C-CS1 IDLE)
 	 ;(mps-state C-CS2 IDLE)
	 ;(mps-state C-DS IDLE)
 	 ;(mps-state C-RS1 IDLE)
 	 ;(mps-state C-RS2 IDLE)

	 (wp-cap-color cg1 CAP_GREY)
	 (wp-cap-color cg2 CAP_GREY)
	 (wp-cap-color cg3 CAP_GREY)
	 (wp-on-shelf cg1 C-CS1 LEFT)
	 (wp-on-shelf cg2 C-CS1 MIDDLE)
	 (wp-on-shelf cg3 C-CS1 RIGHT)

	 (wp-cap-color cb1 CAP_BLACK)
	 (wp-cap-color cb2 CAP_BLACK)
	 (wp-cap-color cb3 CAP_BLACK)
	 (wp-on-shelf cb1 C-CS2 LEFT)
	 (wp-on-shelf cb2 C-CS2 MIDDLE)
	 (wp-on-shelf cb3 C-CS2 RIGHT)
   

   
         (order-complexity o1 c0)
         (order-base-color o1 BASE_RED)
         (order-cap-color o1 CAP_GREY)
         (order-gate o1 GATE-2)
      

	 ; C0 order
	 ;(order-complexity o1 c0)
	 ;(order-base-color o1 BASE_BLACK)
	 ;(order-cap-color o1 CAP_GREY)
	 ;(order-gate o1 GATE-1)

	 ; These values are for the static default world
   (= (path-length C-BS INPUT C-BS OUTPUT) 3.026)
(= (path-length C-BS INPUT C-CS1 INPUT) 10.279)
(= (path-length C-BS INPUT C-CS1 OUTPUT) 11.667)
(= (path-length C-BS INPUT C-CS2 INPUT) 4.011)
(= (path-length C-BS INPUT C-CS2 OUTPUT) 3.034)
(= (path-length C-BS INPUT C-DS INPUT) 5.558)
(= (path-length C-BS INPUT C-DS OUTPUT) 8.556)
(= (path-length C-BS INPUT C-RS1 INPUT) 12.237)
(= (path-length C-BS INPUT C-RS1 OUTPUT) 12.651)
(= (path-length C-BS INPUT C-RS2 INPUT) 3.830)
(= (path-length C-BS INPUT C-RS2 OUTPUT) 2.456)
(= (path-length C-BS OUTPUT C-BS INPUT) 3.026)
(= (path-length C-BS OUTPUT C-CS1 INPUT) 8.431)
(= (path-length C-BS OUTPUT C-CS1 OUTPUT) 10.173)
(= (path-length C-BS OUTPUT C-CS2 INPUT) 1.840)
(= (path-length C-BS OUTPUT C-CS2 OUTPUT) 3.913)
(= (path-length C-BS OUTPUT C-DS INPUT) 5.138)
(= (path-length C-BS OUTPUT C-DS OUTPUT) 7.451)
(= (path-length C-BS OUTPUT C-RS1 INPUT) 10.388)
(= (path-length C-BS OUTPUT C-RS1 OUTPUT) 10.803)
(= (path-length C-BS OUTPUT C-RS2 INPUT) 4.708)
(= (path-length C-BS OUTPUT C-RS2 OUTPUT) 4.213)
(= (path-length C-CS1 INPUT C-BS INPUT) 10.279)
(= (path-length C-CS1 INPUT C-BS OUTPUT) 8.431)
(= (path-length C-CS1 INPUT C-CS1 OUTPUT) 3.647)
(= (path-length C-CS1 INPUT C-CS2 INPUT) 7.247)
(= (path-length C-CS1 INPUT C-CS2 OUTPUT) 8.067)
(= (path-length C-CS1 INPUT C-DS INPUT) 7.476)
(= (path-length C-CS1 INPUT C-DS OUTPUT) 5.851)
(= (path-length C-CS1 INPUT C-RS1 INPUT) 3.090)
(= (path-length C-CS1 INPUT C-RS1 OUTPUT) 3.504)
(= (path-length C-CS1 INPUT C-RS2 INPUT) 8.082)
(= (path-length C-CS1 INPUT C-RS2 OUTPUT) 10.536)
(= (path-length C-CS1 OUTPUT C-BS INPUT) 11.667)
(= (path-length C-CS1 OUTPUT C-BS OUTPUT) 10.173)
(= (path-length C-CS1 OUTPUT C-CS1 INPUT) 3.647)
(= (path-length C-CS1 OUTPUT C-CS2 INPUT) 8.989)
(= (path-length C-CS1 OUTPUT C-CS2 OUTPUT) 9.455)
(= (path-length C-CS1 OUTPUT C-DS INPUT) 6.548)
(= (path-length C-CS1 OUTPUT C-DS OUTPUT) 4.138)
(= (path-length C-CS1 OUTPUT C-RS1 INPUT) 2.909)
(= (path-length C-CS1 OUTPUT C-RS1 OUTPUT) 1.195)
(= (path-length C-CS1 OUTPUT C-RS2 INPUT) 9.470)
(= (path-length C-CS1 OUTPUT C-RS2 OUTPUT) 11.052)
(= (path-length C-CS2 INPUT C-BS INPUT) 4.011)
(= (path-length C-CS2 INPUT C-BS OUTPUT) 1.840)
(= (path-length C-CS2 INPUT C-CS1 INPUT) 7.247)
(= (path-length C-CS2 INPUT C-CS1 OUTPUT) 8.989)
(= (path-length C-CS2 INPUT C-CS2 OUTPUT) 4.162)
(= (path-length C-CS2 INPUT C-DS INPUT) 5.387)
(= (path-length C-CS2 INPUT C-DS OUTPUT) 6.267)
(= (path-length C-CS2 INPUT C-RS1 INPUT) 9.205)
(= (path-length C-CS2 INPUT C-RS1 OUTPUT) 9.619)
(= (path-length C-CS2 INPUT C-RS2 INPUT) 4.958)
(= (path-length C-CS2 INPUT C-RS2 OUTPUT) 4.462)
(= (path-length C-CS2 OUTPUT C-BS INPUT) 3.034)
(= (path-length C-CS2 OUTPUT C-BS OUTPUT) 3.913)
(= (path-length C-CS2 OUTPUT C-CS1 INPUT) 8.067)
(= (path-length C-CS2 OUTPUT C-CS1 OUTPUT) 9.455)
(= (path-length C-CS2 OUTPUT C-CS2 INPUT) 4.162)
(= (path-length C-CS2 OUTPUT C-DS INPUT) 3.346)
(= (path-length C-CS2 OUTPUT C-DS OUTPUT) 6.344)
(= (path-length C-CS2 OUTPUT C-RS1 INPUT) 10.025)
(= (path-length C-CS2 OUTPUT C-RS1 OUTPUT) 10.439)
(= (path-length C-CS2 OUTPUT C-RS2 INPUT) 1.618)
(= (path-length C-CS2 OUTPUT C-RS2 OUTPUT) 3.485)
(= (path-length C-DS INPUT C-BS INPUT) 5.558)
(= (path-length C-DS INPUT C-BS OUTPUT) 5.138)
(= (path-length C-DS INPUT C-CS1 INPUT) 7.476)
(= (path-length C-DS INPUT C-CS1 OUTPUT) 6.548)
(= (path-length C-DS INPUT C-CS2 INPUT) 5.387)
(= (path-length C-DS INPUT C-CS2 OUTPUT) 3.346)
(= (path-length C-DS INPUT C-DS OUTPUT) 3.437)
(= (path-length C-DS INPUT C-RS1 INPUT) 9.295)
(= (path-length C-DS INPUT C-RS1 OUTPUT) 7.581)
(= (path-length C-DS INPUT C-RS2 INPUT) 3.361)
(= (path-length C-DS INPUT C-RS2 OUTPUT) 5.815)
(= (path-length C-DS OUTPUT C-BS INPUT) 8.556)
(= (path-length C-DS OUTPUT C-BS OUTPUT) 7.451)
(= (path-length C-DS OUTPUT C-CS1 INPUT) 5.851)
(= (path-length C-DS OUTPUT C-CS1 OUTPUT) 4.138)
(= (path-length C-DS OUTPUT C-CS2 INPUT) 6.267)
(= (path-length C-DS OUTPUT C-CS2 OUTPUT) 6.344)
(= (path-length C-DS OUTPUT C-DS INPUT) 3.437)
(= (path-length C-DS OUTPUT C-RS1 INPUT) 6.885)
(= (path-length C-DS OUTPUT C-RS1 OUTPUT) 5.171)
(= (path-length C-DS OUTPUT C-RS2 INPUT) 6.359)
(= (path-length C-DS OUTPUT C-RS2 OUTPUT) 7.941)
(= (path-length C-RS1 INPUT C-BS INPUT) 12.237)
(= (path-length C-RS1 INPUT C-BS OUTPUT) 10.388)
(= (path-length C-RS1 INPUT C-CS1 INPUT) 3.090)
(= (path-length C-RS1 INPUT C-CS1 OUTPUT) 2.909)
(= (path-length C-RS1 INPUT C-CS2 INPUT) 9.205)
(= (path-length C-RS1 INPUT C-CS2 OUTPUT) 10.025)
(= (path-length C-RS1 INPUT C-DS INPUT) 9.295)
(= (path-length C-RS1 INPUT C-DS OUTPUT) 6.885)
(= (path-length C-RS1 INPUT C-RS1 OUTPUT) 2.766)
(= (path-length C-RS1 INPUT C-RS2 INPUT) 10.040)
(= (path-length C-RS1 INPUT C-RS2 OUTPUT) 12.493)
(= (path-length C-RS1 OUTPUT C-BS INPUT) 12.651)
(= (path-length C-RS1 OUTPUT C-BS OUTPUT) 10.803)
(= (path-length C-RS1 OUTPUT C-CS1 INPUT) 3.504)
(= (path-length C-RS1 OUTPUT C-CS1 OUTPUT) 1.195)
(= (path-length C-RS1 OUTPUT C-CS2 INPUT) 9.619)
(= (path-length C-RS1 OUTPUT C-CS2 OUTPUT) 10.439)
(= (path-length C-RS1 OUTPUT C-DS INPUT) 7.581)
(= (path-length C-RS1 OUTPUT C-DS OUTPUT) 5.171)
(= (path-length C-RS1 OUTPUT C-RS1 INPUT) 2.766)
(= (path-length C-RS1 OUTPUT C-RS2 INPUT) 10.454)
(= (path-length C-RS1 OUTPUT C-RS2 OUTPUT) 12.085)
(= (path-length C-RS2 INPUT C-BS INPUT) 3.830)
(= (path-length C-RS2 INPUT C-BS OUTPUT) 4.708)
(= (path-length C-RS2 INPUT C-CS1 INPUT) 8.082)
(= (path-length C-RS2 INPUT C-CS1 OUTPUT) 9.470)
(= (path-length C-RS2 INPUT C-CS2 INPUT) 4.958)
(= (path-length C-RS2 INPUT C-CS2 OUTPUT) 1.618)
(= (path-length C-RS2 INPUT C-DS INPUT) 3.361)
(= (path-length C-RS2 INPUT C-DS OUTPUT) 6.359)
(= (path-length C-RS2 INPUT C-RS1 INPUT) 10.040)
(= (path-length C-RS2 INPUT C-RS1 OUTPUT) 10.454)
(= (path-length C-RS2 INPUT C-RS2 OUTPUT) 3.002)
(= (path-length C-RS2 OUTPUT C-BS INPUT) 2.456)
(= (path-length C-RS2 OUTPUT C-BS OUTPUT) 4.213)
(= (path-length C-RS2 OUTPUT C-CS1 INPUT) 10.536)
(= (path-length C-RS2 OUTPUT C-CS1 OUTPUT) 11.052)
(= (path-length C-RS2 OUTPUT C-CS2 INPUT) 4.462)
(= (path-length C-RS2 OUTPUT C-CS2 OUTPUT) 3.485)
(= (path-length C-RS2 OUTPUT C-DS INPUT) 5.815)
(= (path-length C-RS2 OUTPUT C-DS OUTPUT) 7.941)
(= (path-length C-RS2 OUTPUT C-RS1 INPUT) 12.493)
(= (path-length C-RS2 OUTPUT C-RS1 OUTPUT) 12.085)
(= (path-length C-RS2 OUTPUT C-RS2 INPUT) 3.002)
(= (path-length START INPUT C-BS INPUT) 3.502)
(= (path-length START INPUT C-BS OUTPUT) 1.331)
(= (path-length START INPUT C-CS1 INPUT) 7.804)
(= (path-length START INPUT C-CS1 OUTPUT) 9.545)
(= (path-length START INPUT C-CS2 INPUT) 1.213)
(= (path-length START INPUT C-CS2 OUTPUT) 3.653)
(= (path-length START INPUT C-DS INPUT) 4.878)
(= (path-length START INPUT C-DS OUTPUT) 6.823)
(= (path-length START INPUT C-RS1 INPUT) 9.761)
(= (path-length START INPUT C-RS1 OUTPUT) 10.175)
(= (path-length START INPUT C-RS2 INPUT) 4.449)
(= (path-length START INPUT C-RS2 OUTPUT) 3.953)

	)

	(:goal (order-fulfilled o1))
)
    